couponService2:
  url: http://localhost:9091/couponapi/
server:
  port: 9090
spring:
  datasource:
    password: ${password}
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${username}
